### ISSUE TITLE
大佬，我这个问题是咋回事

### ISSUE THREAD

**Issue by 929126387** [DHDAXCW/OpenWrt_X86_X64#11]
昨天软路由刷了您的固件，，，昨天用的hello word 当天好用 ，今早发现上不去了，需要进入op helloword插件 点击应用保存，才恢复，是插件崩溃了吗？
![QQ截图20220413090509](https://user-images.githubusercontent.com/77496052/163083784-c7fe9794-6547-490d-b46c-f4f8c472143c.png)

**Comment by DHDAXCW** [comment]
等今天版本
