### ISSUE TITLE
大佬，有时间可以打一下这个补丁吗，修复kmod-iwlwifi kernel5.15依赖问题的

### ISSUE THREAD

**Issue by shiyipeng210** [DHDAXCW/OpenWrt_X86_X64#12]
https://github.com/WYC-2020/lede/blob/0bdae446b37ca151de2c17902635df59770c5c25/target/linux/generic/backport-5.15/001-fix-kmod-iwlwifi-build-on-kernel-5.15.patch

谢谢大佬

**Comment by DHDAXCW** [comment]
啊这，，，没看到 等下次加吧 我刚刚编译忘记看

**Comment by shiyipeng210** [comment]
不好意思又来打扰,我下载了最新的固件包,kmod-iwlwifi依旧无法安装,大佬看看有没有办法能解决下,谢谢

**Comment by DHDAXCW** [comment]
没有了，让他隐藏起来了
