### ISSUE TITLE
intel T550网卡，被默认在千兆状态。

### ISSUE THREAD

**Issue by nono8273** [DHDAXCW/OpenWrt_X86_X64#26]
另一头接口是电脑的2.5G的接口。之前在[sirpdboy]的固件中能正常识别为2.5G，换了大大固件，发现了这个BUG。。不知应该怎么处理。

日志因为字数，无法贴完整，望见谅
Sat Jan  3 23:49:46 2009 kern.info kernel: [  103.687254] pps pps1: new PPS source ptp1
Sat Jan  3 23:49:46 2009 kern.info kernel: [  103.687598] ixgbe 0000:03:00.1: registered PHC device on eth2
Sat Jan  3 23:49:46 2009 kern.info kernel: [  103.814138] 8021q: adding VLAN 0 to HW filter on device eth2
Sat Jan  3 23:50:01 2009 kern.info kernel: [  118.814798] ixgbe 0000:03:00.0: removed PHC on eth1
Sat Jan  3 23:50:02 2009 daemon.notice netifd: Interface 'wan6' is disabled
Sat Jan  3 23:50:02 2009 daemon.notice netifd: Interface 'wan6' is enabled
Sat Jan  3 23:50:15 2009 kern.info kernel: [  132.723620] pps pps0: new PPS source ptp0
Sat Jan  3 23:50:15 2009 kern.info kernel: [  132.723953] ixgbe 0000:03:00.0: registered PHC device on eth1
Sat Jan  3 23:50:15 2009 kern.info kernel: [  132.845236] 8021q: adding VLAN 0 to HW filter on device eth1
Sat Jan  3 23:50:15 2009 kern.info kernel: [  132.845713] br-lan: port 2(eth1) entered blocking state
Sat Jan  3 23:50:15 2009 kern.info kernel: [  132.846067] br-lan: port 2(eth1) entered disabled state
Sat Jan  3 23:50:15 2009 kern.info kernel: [  132.846507] device eth1 entered promiscuous mode
Sat Jan  3 23:50:34 2009 daemon.notice netifd: Interface 'lan' is now down
Sat Jan  3 23:50:34 2009 daemon.info avahi-daemon[8139]: Withdrawing address record for 192.168.11.1 on br-lan.
Sat Jan  3 23:50:34 2009 daemon.info avahi-daemon[8139]: Leaving mDNS multicast group on interface br-lan.IPv4 with address 192.168.11.1.
Sat Jan  3 23:50:34 2009 daemon.info avahi-daemon[8139]: Interface br-lan.IPv4 no longer relevant for mDNS.
Sat Jan  3 23:50:34 2009 daemon.info avahi-daemon[8139]: Interface br-lan.IPv6 no longer relevant for mDNS.
Sat Jan  3 23:50:34 2009 daemon.info avahi-daemon[8139]: Leaving mDNS multicast group on interface br-lan.IPv6 with address fe80::20c:29ff:fe13:f96.
Sat Jan  3 23:50:34 2009 kern.info kernel: [  151.456660] br-lan: port 1(eth0) entered disabled state
Sat Jan  3 23:50:34 2009 kern.info kernel: [  151.458597] device eth0 left promiscuous mode
Sat Jan  3 23:50:34 2009 kern.info kernel: [  151.460431] br-lan: port 1(eth0) entered disabled state
Sat Jan  3 23:50:34 2009 daemon.info avahi-daemon[8139]: Withdrawing address record for fe80::20c:29ff:fe13:f96 on br-lan.
Sat Jan  3 23:50:34 2009 kern.info kernel: [  151.623726] device eth1 left promiscuous mode
Sat Jan  3 23:50:34 2009 kern.info kernel: [  151.624098] br-lan: port 2(eth1) entered disabled state
Sat Jan  3 23:50:34 2009 kern.info kernel: [  151.654151] ixgbe 0000:03:00.0: removed PHC on eth1
Sat Jan  3 23:50:35 2009 daemon.notice netifd: Interface 'lan' is disabled
Sat Jan  3 23:50:35 2009 daemon.notice netifd: Interface 'lan' has link connectivity loss
Sat Jan  3 23:50:35 2009 daemon.notice netifd: Interface 'lan' has link connectivity
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.190409] 8021q: adding VLAN 0 to HW filter on device eth0
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.191094] br-lan: port 1(eth0) entered blocking state
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.191389] br-lan: port 1(eth0) entered disabled state
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.193359] device eth0 entered promiscuous mode
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.203447] e1000: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: None
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.213261] pps pps0: new PPS source ptp0
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.213514] ixgbe 0000:03:00.0: registered PHC device on eth1
Sat Jan  3 23:50:35 2009 daemon.notice netifd: Interface 'lan' is enabled
Sat Jan  3 23:50:35 2009 daemon.notice netifd: Interface 'lan' is setting up now
Sat Jan  3 23:50:35 2009 daemon.info avahi-daemon[8139]: Joining mDNS multicast group on interface br-lan.IPv4 with address 192.168.88.1.
Sat Jan  3 23:50:35 2009 daemon.info avahi-daemon[8139]: New relevant interface br-lan.IPv4 for mDNS.
Sat Jan  3 23:50:35 2009 daemon.info avahi-daemon[8139]: Registering new address record for 192.168.88.1 on br-lan.IPv4.
Sat Jan  3 23:50:35 2009 daemon.notice netifd: Interface 'lan' is now up
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.335044] 8021q: adding VLAN 0 to HW filter on device eth1
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.335480] br-lan: port 2(eth1) entered blocking state
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.335755] br-lan: port 2(eth1) entered disabled state
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.336082] device eth1 entered promiscuous mode
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.336737] br-lan: port 1(eth0) entered blocking state
Sat Jan  3 23:50:35 2009 kern.info kernel: [  152.337022] br-lan: port 1(eth0) entered forwarding state
Sat Jan  3 23:50:36 2009 user.notice firewall: Reloading firewall due to ifup of lan (br-lan)
Sat Jan  3 23:50:36 2009 user.notice nlbwmon: Reloading nlbwmon due to ifup of lan (br-lan)
Sat Jan  3 23:50:36 2009 daemon.err odhcpd[6406]: Failed to send to ff02::1%lan@br-lan (Address not available)
Sat Jan  3 23:50:36 2009 authpriv.info dropbear[7650]: Early exit: Terminated by signal
Sat Jan  3 23:50:36 2009 authpriv.info dropbear[23268]: Not backgrounding
Sat Jan  3 23:50:36 2009 daemon.info avahi-daemon[8139]: Joining mDNS multicast group on interface br-lan.IPv6 with address fe80::20c:29ff:fe13:f96.
Sat Jan  3 23:50:36 2009 daemon.info avahi-daemon[8139]: New relevant interface br-lan.IPv6 for mDNS.
Sat Jan  3 23:50:36 2009 daemon.info avahi-daemon[8139]: Registering new address record for fe80::20c:29ff:fe13:f96 on br-lan.*.
Sat Jan  3 23:51:44 2009 daemon.notice netifd: Network device 'eth1' link is up
Sat Jan  3 23:51:44 2009 kern.info kernel: [  221.542550] ixgbe 0000:03:00.0 eth1: NIC Link is Up 1 Gbps, Flow Control: None
Sat Jan  3 23:51:44 2009 kern.info kernel: [  221.543444] br-lan: port 2(eth1) entered blocking state
Sat Jan  3 23:51:44 2009 kern.info kernel: [  221.543806] br-lan: port 2(eth1) entered forwarding state
Sat Jan  3 23:53:07 2009 daemon.notice netifd: Network device 'eth1' link is down
Sat Jan  3 23:53:07 2009 kern.info kernel: [  304.664183] ixgbe 0000:03:00.0 eth1: NIC Link is Down
Sat Jan  3 23:53:07 2009 kern.info kernel: [  304.666204] br-lan: port 2(eth1) entered disabled state
Sat Jan  3 23:54:53 2009 daemon.notice netifd: Network device 'eth1' link is up
Sat Jan  3 23:54:53 2009 kern.info kernel: [  410.039074] ixgbe 0000:03:00.0 eth1: NIC Link is Up 1 Gbps, Flow Control: None
Sat Jan  3 23:54:53 2009 kern.info kernel: [  410.039838] br-lan: port 2(eth1) entered blocking state
Sat Jan  3 23:54:53 2009 kern.info kernel: [  410.040200] br-lan: port 2(eth1) entered forwarding state

**Comment by DHDAXCW** [comment]
等刷5.15  今天版本
