### ISSUE TITLE
 x86-64-Linux-5.15_Docker版_全插件   大佬下个版本能不能增加个微信推送    

### ISSUE THREAD

**Issue by lskc3389** [DHDAXCW/OpenWrt_X86_X64#29]

**Comment by DHDAXCW** [comment]
全能推送那个不好用嘛？

**Comment by 0x676e67** [comment]
加个 

kmod-usb-net-ipheth, 

kmod-usb-net-rndis
--


<br class="Apple-interchange-newline">
--


<br class="Apple-interchange-newline">
