### ISSUE TITLE
执行lean.sh报错，认证失败

### ISSUE THREAD

**Issue by xrouterservice** [DHDAXCW/OpenWrt_X86_X64#31]
Checked out revision 33858.
svn: E170013: Unable to connect to a repository at URL 'https://github.com/zcy85611/Openwrt-Package/trunk/luci-udptools'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
svn: E170013: Unable to connect to a repository at URL 'https://github.com/zcy85611/Openwrt-Package/trunk/udp2raw'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
svn: E170013: Unable to connect to a repository at URL 'https://github.com/zcy85611/Openwrt-Package/trunk/udpspeeder'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

**Comment by DHDAXCW** [comment]
可以移除这三个东西，它已没有用了。https://github.com/DHDAXCW/OpenWRT_x86_x64/commit/b86592f5d870bdc853cfc5aa3988f80e26c66f3d
