### ISSUE TITLE
建议固件加上kmod-usb3驱动

### ISSUE THREAD

**Issue by xt101** [DHDAXCW/OpenWrt_X86_X64#39]

**Comment by DHDAXCW** [comment]
用它做什么？

**Comment by xt101** [comment]
> 用它做什么？

大佬，usb有线网卡没有这个驱动好像不稳定。usb网卡连接电脑关机再重启后显示断线。3.0驱动增加3.0设备支持

**Comment by DHDAXCW** [comment]
> > 用它做什么？
> 
> 大佬，usb有线网卡没有这个驱动好像不稳定。usb网卡连接电脑关机再重启后显示断线。3.0驱动增加3.0设备支持

安排 明天~

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/OpenWRT_x86_x64/commit/30ceaa7e3a1e6f3e99f7d55f3a3d9d15c61924c4

**Comment by xt101** [comment]
谢谢

**Comment by xt101** [comment]
> [30ceaa7](https://github.com/DHDAXCW/OpenWRT_x86_x64/commit/30ceaa7e3a1e6f3e99f7d55f3a3d9d15c61924c4)

刷了11月23号79版本固件，重启后显示连接，但wan口没有信号了。

**Comment by DHDAXCW** [comment]
> 

 有物理接口吗？

**Comment by xt101** [comment]
> > 
> 
> 有物理接口吗？

有的，物理接口都能正常显示。

**Comment by xt101** [comment]
装了24号的固件，重启正常了。
