### ISSUE TITLE
Passwall2在使用时，偶尔某个时间段CPU使用过高，导致openwrt程序重启

### ISSUE THREAD

**Issue by bruceywave** [DHDAXCW/OpenWrt_X86_X64#47]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/8263729/216797025-f93672ef-bbd2-4970-be4c-9d11a37f84d7.png">
<img width="848" alt="image" src="https://user-images.githubusercontent.com/8263729/216797029-91dd9931-d174-47f2-a79e-1b1d8c36ebd4.png">
<img width="848" alt="image" src="https://user-images.githubusercontent.com/8263729/216797047-834d8907-d3fb-43f8-8fc8-7e0df6b0778e.png">
<img width="848" alt="image" src="https://user-images.githubusercontent.com/8263729/216797056-4d8dcdf7-f5d7-4294-a6d4-b9713698c3cf.png">
重启后，又看不到重启之前的日志，为什么重启

**Comment by ZhuangJiayu** [comment]
我也遇到了
