### ISSUE TITLE
请问这个固件只能写入到U盘等移动存储插在软路由上启动吗？

### ISSUE THREAD

**Issue by leige87** [DHDAXCW/OpenWrt_X86_X64#52]
请问这个固件只能写入到U盘等移动存储插在软路由上启动吗？我写入到本地硬盘后，启动出现error1962，无论怎样设置都是这个提示，但写入U盘就可以正常启动，求助求助，有没有大神帮忙解决一下，给出个奇招！

**Comment by DHDAXCW** [comment]
换个硬盘试试？

**Comment by leige87** [comment]
不是硬盘的事，和主机有关系，有的联想三代四代intel平台的就不行，Legacy模式和UEFI都试过了，但换了高版本的或者AMD平台就可以，我就想解决下这个问题，看有没有大神能把这个难题解了

**Comment by szfelix11** [comment]
我的J4125刷这版固件硬盘无法启动，刷UEFI或Legacy没问题，用惯了这个固件，希望能解决
