### ISSUE TITLE
最近经常遇到重启的情况

### ISSUE THREAD

**Issue by zJanch** [DHDAXCW/OpenWrt_X86_X64#53]
最近经常遇到重启的情况，不知道啥原因

**Comment by DHDAXCW** [comment]
等会换5.15内核吧

**Comment by icodex** [comment]
5.15版本也经常遇到重启，一天重启好几次。

**Comment by xuanranran** [comment]
6.1.x和5.15.116都会莫名重启

**Comment by xuanranran** [comment]
> 等会换5.15内核吧
5.15.116和6.1.3x都不稳定

**Comment by xuanranran** [comment]
> 等会换5.15内核吧

5.15.116和6.1.3x内核不稳定 时不时会自动重启
