### ISSUE TITLE
遇到了PPPoE掉线不重连的问题

### ISSUE THREAD

**Issue by finch-ift** [DHDAXCW/OpenWrt_X86_X64#54]
两天或四天会出现PPPoE掉线不重连，局域网正常但无法上网需要关闭PPPoE然后重新连接才能上网，系统日志中没有报错
PVE下的虚拟机环境(网卡使用了直通)

**Comment by finch-ift** [comment]
[Powered by LuCI Master (git-23.097.24904-853d455)](https://github.com/coolsnowwolf/luci) / OpenWrt R23.4.1 (2023-04-10)

**Comment by greenhat616** [comment]
+1 我也遇到了
