### ISSUE TITLE
关于release只有source文件

### ISSUE THREAD

**Issue by yikexiaoyao** [DHDAXCW/OpenWrt_X86_X64#69]
请问为什么release只有source文件，没有固件

**Comment by KPI0** [comment]
> 请问为什么release只有source文件，没有固件

要看actions，成功才有

**Comment by yikexiaoyao** [comment]
好像是被取消了

**Comment by DHDAXCW** [comment]
一直是rust报错，不知道咋回事。换其他人电脑托管没毛病，只有我服务器不行，估计得重装了。。。
