### ISSUE TITLE
Adguardhome

### ISSUE THREAD

**Issue by oppen123** [DHDAXCW/OpenWRT_x86_x64#71]
Adguardhome一直显示已启用无法关闭，打开3000端口显示404 page not found

**Comment by DHDAXCW** [comment]
问题已解决，等明天发布新版本，感谢反馈
![image](https://github.com/DHDAXCW/OpenWRT_x86_x64/assets/74764072/adf1ae8d-fb77-43f1-a410-161834defdcd)

**Comment by oppen123** [comment]
没事没事谢谢大佬
