### ISSUE TITLE
docker貌似出了些小问题

### ISSUE THREAD

**Issue by LemonLatteFizz** [DHDAXCW/OpenWrt_X86_X64#74]
不影响使用的小问题，本来应该在电报群说的，结果绝了...号被电报封了，正在申诉😂

系统重启后进管理页面点docker栏就会显示下图这样，十几秒到半分钟左右会恢复正常，感觉是启动卡了一下，之前版本没遇到过，不知道会不会有其他影响。

<img width="1073" alt="屏幕截图 2024-04-06 010220" src="https://github.com/DHDAXCW/OpenWRT_x86_x64/assets/18193702/71e63666-ea3c-458a-850f-d37d9fc1a724">

部分日志
![image](https://github.com/DHDAXCW/OpenWRT_x86_x64/assets/18193702/954fb2eb-210f-472e-82e1-be9edf5f71b3)

![image](https://github.com/DHDAXCW/OpenWRT_x86_x64/assets/18193702/c7346973-452a-49e9-ba82-5cba1659e0c1)

**Comment by LemonLatteFizz** [comment]
一觉醒来被电报的反垃圾邮件系统ban了，莫名其妙，还在申诉，现在电报群和私聊都不能发消息😂

**Comment by ohyeah521** [comment]
路由器不玩docker保平安，路由器厂商为了高价卖路由器，弄个docker功能，然后加价300，路由器的核心就是稳，其它都是扯淡

**Comment by LemonLatteFizz** [comment]
有没有一种可能，提供上网基础服务有硬路由，软路由只是提供扩展功能...

**Comment by DHDAXCW** [comment]
等我把电报机器人给日了

**Comment by DHDAXCW** [comment]
改好了，等晚上再试试

**Comment by LemonLatteFizz** [comment]
感谢骷髅佬！😘❤️
