### ISSUE TITLE
后台更新失败

### ISSUE THREAD

**Issue by marszh580** [DHDAXCW/OpenWrt_X86_X64#77]
您好，

我是小白一枚，在openwrt界久仰您的大名，感谢您的付出。
从418版开始使用您的固件，感觉清爽简洁，所有常用的功能基本全都包括了，非常喜欢。423更新后尝试后台更新，但两次都失败了。不知道我的方法是都正确，下载最新固件-系统-备份更新-上传固件-刷写，同样的方法两次失败，解压后也试了一下，同样也失败了，麻烦您指教一下，毕竟不希望每次都重新安装的，感谢🙏。

**Comment by DHDAXCW** [comment]
内存要4GB以上

**Comment by marszh580** [comment]
好的。我回去试一下。硬盘不需要调整吧？谢谢您🙏

**Comment by marszh580** [comment]
还有一个问题想请教您一下，想导入ssl证书进行安全访问，发现系统已经安装了ssl插件，但找不到uhttpd，我应该怎么做呢？搜索了很久一直没找到合适的答案，麻烦您了。

**Comment by marszh580** [comment]
> 内存要4GB以上

将内存扩容到4G后升级两次未成功，解压后再试，成功了。

**Comment by tom5920** [comment]
![image](https://github.com/DHDAXCW/OpenWRT_x86_x64/assets/162852929/2e5cf72a-14f1-4f28-93ae-b7b7472ad17b)
2G一样流畅

**Comment by marszh580** [comment]
> 内存要4GB以上
您好，上次增加内存到4G后台更新后，系统运行正常，但内存占用很高，不知道是否正常。
<img width="1182" alt="截屏2024-05-04 09 33 57" src="https://github.com/DHDAXCW/OpenWRT_x86_x64/assets/65878050/5ee3143d-75d5-47bc-956b-32d2254e4785">

**Comment by IngwerHe** [comment]
作者能不能帮忙把hello world加进去呀？passwall用不习惯

**Comment by DHDAXCW** [comment]
> 作者能不能帮忙把hello world加进去呀？passwall用不习惯

helloworld早跑了怎么加进去？
