### ISSUE TITLE
端口转发不生效

### ISSUE THREAD

**Issue by willjayyyy** [DHDAXCW/OpenWrt_X86_X64#79]
通过公网访问，通过NAT环回访问，均无法成功转发
![image](https://github.com/DHDAXCW/OpenWRT_x86_x64/assets/67086243/4dce1e32-dc0a-4528-bfee-b2786f3ec7c5)
安装包为2024.05.06-docker-openwrt-x86-64-squashfs-efi.img

**Comment by DHDAXCW** [comment]
把sfe关了看看？
